### ISSUE TITLE
nlog endpoint address not transformed

### ISSUE THREAD

**Issue by gilm0079** [sayedihashimi/slow-cheetah#107]
I just upgraded my SlowCheetah version last week.  Today we noticed that our production .config file did not transform the endpoint address for nlog.  The previous version of slow cheetah worked fine with this.  We also have RIA service model endpoints and appsettings in the same config.  Those transformed correctly.  The nlog one was the only one that did not.  I'll be rolling back to the previous version of slowcheetah for now.

Latest version of slow cheetah that has the bug: 2.5.7.1 extension for VS
Rolling back to 2.5.5 for now.

**Comment by davilimap** [comment]
If this is still a problem, test with the newest version and reopen the issue if the wrong behavior persists.
