### ISSUE TITLE
Package restore now handled by NuGet 2.7

### ISSUE THREAD

**Issue by Jaans** [sayedihashimi/slow-cheetah#109]
Thanks for a very useful tool Sayed.

With NuGet 2.7 Package Restore is now automatic and with implied consent. The package restore mechanism has changed to address the very issue of Build Targets that come from NuGet packages. It even includes a way to resolve this issue for Build Servers (like TFS Build, TeamCity, etc.). See the following links for more:
- http://docs.nuget.org/docs/workflows/migrating-to-automatic-package-restore
- http://docs.nuget.org/docs/reference/package-restore-with-team-build

As a result, your current extension / NuGet package should no longer be creating the packageRestore.proj file as this is now taken care of by NuGet. Would you please remove it as a default action for the tool when adding a transform?

**Comment by davilimap** [comment]
Full NuGet support is now available after #203
