### ISSUE TITLE
Can not compile because dll-missing error?

### ISSUE THREAD

**Issue by thimmey** [sayedihashimi/slow-cheetah#114]
I just installed VS2013 and compiled my project. everything worked. After Iadded SlowCheetah I get the following error during compilation.

The SlowCheetah.Xdt.TransformXml-Task could not be loaded from the C:\Users\User\AppData\Local\Microsoft\MSBuild\SlowCheetah\v2.5.10\SlowCheetah.Xdt.dll-Assembly. The File or Assembly "file:///C:\Users\User\AppData\Local\Microsoft\MSBuild\SlowCheetah\v2.5.10\SlowCheetah.Xdt.dll" or a dependency could not bge found. The system could not find the file. Make sure that the <UsingTask>-declaration is correct, that the assembly and all dependencys are available and that the task contains a public class which implements Microsoft.Build.Framework.ITask.

Kind Regards
Tim

**Comment by sayedihashimi** [comment]
FYI for compilation users don't need to install the SlowCheetah Visual Studio extension, just the NuGet package into the project. You just need the Visual Studio extension to ***Add Transforms*** to a project. Running transforms happens at build and uses .targets in the NuGet package so no need for all users to install the extension.

**Comment by wilson0x4d** [comment]
we don't say thanks enough, but I have to note that every time I've had a concern with SlowCheetah you've consistently managed to find a solution. i am still using slowcheetah today, depending on the project at hand, and wanted to say thanks for all the hard work you put in (and may even continue to put in) on this tooling.

i wish that Microsoft could pull this in as first-class functionality within Visual Studio. this fills an important role for many devs out there, and there's a huge void that requires manual tooling without it.

THANK YOU.
