### ISSUE TITLE
SlowCheetah.Transforms.targets gets deployed with WebDeploy

### ISSUE THREAD

**Issue by kipusoep** [sayedihashimi/slow-cheetah#119]
Using version 2.5.10.3.

SlowCheetah includes a file called 'SlowCheetah.Transforms.targets' in the 'Properties\SlowCheetah\' folder.
This item has a Build Action of 'Content', which causes the file to get deployed to the server with WebDeploy.
This is unnecessary and should be avoided.

Great package btw, thanks!

**Comment by davilimap** [comment]
The targets file is now part of the NuGet package and so, is no longer in the project files

**Comment by bhuvanesh6** [comment]
Slow Cheetah official and unofficial release versions are available in Nuget
