### ISSUE TITLE
SlowCheetah.Transforms.targets does not play nice with TFS Source Control

### ISSUE THREAD

**Issue by Jaans** [sayedihashimi/slow-cheetah#120]
When updating the SlowCheetah NuGet package from .2 to .3, the process fails with error:

TF14092: The item $/.../Properties/SlowCheetah/SlowCheetah.Transforms.targets cannot be changed. A parent of this item has a pending delete which must be checked in first.

Note: Prior to performing the NuGet package update, there were no pending changes.

See screenshot: http://i.imgur.com/kh4CLGC.png

**Comment by davilimap** [comment]
The targets file has been moved to the NuGet package and so, is no longer part of the project files
