### ISSUE TITLE
SlowCheetah.Xdt is not a signed assembly

### ISSUE THREAD

**Issue by wcabus** [sayedihashimi/slow-cheetah#130]
When adding SlowCheetah to a project, you also add a reference to the SlowCheetah.Xdt assembly, which isn't signed (doesn't have a strong name). This prevents your own assemblies to have a strong name.

If you might wonder why you would sign an application assembly: in my case, I need to sign it because the path used by My.Settings changes if you change the location of your exe file, unless ... it is signed.

**Comment by davilimap** [comment]
As of 2.5.48, SlowCheetah only contains signed assemblies.
