### ISSUE TITLE
Announcement: SlowCheetah is in maintence mode

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/slow-cheetah#158]
Hey guys I first developed SlowCheetah around VS2010 SP2 with the idea that I could at some point transition this to the appropriate team(s) at Microsoft. Unfortunately I haven't been able to do that, and the existence of this extension has actually worked against that goal.

I'm really happy that SlowCheetah has gotten the attention and success that it has, but now it's time for me to move on.
### No support for SlowCheetah in VS "14"

I am not planning to update SlowCheetah for Visual Studio "14". If you would like to see support for transforms in VS "14" I suggest you vote, **_and comment**_, on the uesrvoice item at http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2043217-support-web-config-style-transforms-on-any-file-in.
### No new features

I will not be adding any features to SlowCheetah myself. If anyone want's to add any features I will try and help guide anyone who is interested.
### No fixes for regressions

If there are any scenarios that work in VS2013 RTM that do not work in future version of Visual Studio then I will not be fixing them.

I hope you all understand my situation here. I have spent countless hours working on SlowCheetah and there is very little ROI for me so, I need to move on to focus on other OSS projects that I'm involved in.

Thanks for all the love. I still love SlowCheetah too and I'm sad to see there won't be support for transform in VS "14"

**Comment by AndersAbel** [comment]
Thanks Sayed for this great tool that has been indispensable in several projects.

Last week, Microsoft released some more news on SlowCheetah's future in the [UserVoice thread](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2043217-support-web-config-style-transforms-on-any-file-in) that is referenced above.

> While we will not be implementing this functionality in Visual Studio 2015 itself, we do plan to update the SlowCheetah extension to fully support Visual Studio 2015. Our long term plan, however, is to integrate this functionality into a future version of Visual Studio.

**Comment by RehanSaeed** [comment]
Great news. Exactly what we all wanted.

**Comment by tekkonkink** [comment]
Slow Cheetah lives on!

**Comment by dellycowboy** [comment]
Wow it lives! 

Great news! Microsoft listened, some achievement Sayed. 

I also want to add that I have been using it for years, I actually can't imagine not having this feature in VS. Cheers.

**Comment by davidjdriver** [comment]
@sayedihashimi We love SlowCheetah but I just can't believe that it hasn't made it into the normal build templates.

**Comment by sayedihashimi** [comment]
@davidjdriver yes, I'm waiting for that day too.

**Comment by sayedihashimi** [comment]
Thanks for all the positive comments here, I really appreciate it.

**Comment by diegospindola** [comment]
Congratulations for your work in Slow Cheetah. It has helped me a lot through these years. Fortunately the VS team says it plans to support it for VS 2015.

Thank's Sayed!

**Comment by fgiacomelli** [comment]
Hello, some news here? Will it be supported in the next version?

**Comment by mleyb** [comment]
Some of the best news I've heard in weeks! So glad this is making it into VS2015 and eventually into the IDE itself - we have many projects that rely on it

**Comment by WillBuik** [comment]
Hey everyone.

We have a preview release of SlowCheetah up on the VS Gallery with support for Visual Studio 2015.  If anyone is interested in trying it out, you can download it [here](https://visualstudiogallery.msdn.microsoft.com/05bb50e3-c971-4613-9379-acae2cfe6f9e), or just search "SlowCheetah" in Tools->Extensions & Updates.  The preview only supports Visual Studio 2015, but we expect to support more versions soon.

Please let me know if you run into any issues with it and I will try to fix them as soon as possible.

**Comment by mwpowellhtx** [comment]
That's great! Thank you. VS2013 would be great, maybe 2012; unless there are other takers. :+1:

**Comment by stijnherreman** [comment]
@WillBuik it's been afwully quiet since the release of the preview version, 9 months ago. Any update?

**Comment by kpa6uk** [comment]
@WillBuik it's already 13 months passed since the release of the preview version. Any update?

**Comment by jviau** [comment]
[v2.5.48](https://github.com/sayedihashimi/slow-cheetah/releases/tag/v2.5.48) of SlowCheetah has been released. This release supports VS 2012-2017. We also plan to look into more issues, so continue to open issues on this repo as needed.

[Visual Studio Extension](https://marketplace.visualstudio.com/items?itemName=WillBuikMSFT.SlowCheetah-XMLTransforms)
[Nuget Package](https://www.nuget.org/packages/SlowCheetah/2.5.48)

**Comment by mwpowellhtx** [comment]
This is great! :+1:
