### ISSUE TITLE
.config files do not transform in VS 2012 RC

### ISSUE THREAD

**Issue by jhubsharp** [sayedihashimi/slow-cheetah#16]
After switching to VS 2012 RC, it doesn't look like SlowCheetah is transforming files when i publish to my development server. Files are still transforming in 2010 and were fine in 2011 Beta.

**Comment by Ganeshcse** [comment]
Hi Sayed,

Thanks for your utility to solve great problems with config files transformation. Unfortunately I am not sure if this thread is still active to receive answers but some how found that I can still write my comment.

I am using SlowCheetah 2.5.48 version in my VSTO project. I am able to transform the config files in my WPF and Console applications, but when it comes to VSTO project type, the files are not generated after publish.

I have Debug, Release, SIT, UAT and Prod configurations and I have taken all possible precautions. Also I have read in some other articles about publishing with non-web projects (assuming they are talking about class libraries), but some how I could not able to achieve from those links.

Some of the links which I found are below,

http://blogs.clariusconsulting.net/kzu/how-to-apply-build-configuration-transformations-on-non-web-projects/ (Tried this - but no luck for me).

http://stackoverflow.com/questions/3004210/app-config-transformation-for-projects-which-are-not-web-projects-in-visual-stud (Seems long process but tried some of the answers but no-luck).

Would like to know if there is a direct manual or a link on how to get it fixed.

Note:- I am using VSTO project type. I have tried with WPF and Console application where it works perfectly like a gem.

Kindly let me know.

Thanks
