### ISSUE TITLE
Transforms stop when upgrading to 2.5.14. Rollback to 2.5.10.3 and they work fine

### ISSUE THREAD

**Issue by smenchions** [sayedihashimi/slow-cheetah#167]
Recently updated via nuget from :

package id="SlowCheetah" version="2.5.10.3" targetFramework="net45"

To 

package id="SlowCheetah" version="2.5.14" targetFramework="net45" 

and after this update, Slow Cheetah stopped transforming files within VS2013 Ultimate Update 4

I rolled back to 2.5.10.3 and it now works fine again.

**Comment by sayedihashimi** [comment]
I think this should be fixed so I'm closing this. If it's still an issue please reopen.
