### ISSUE TITLE
Exclude node_modules folder from copy commmand on build

### ISSUE THREAD

**Issue by ashclarke** [sayedihashimi/slow-cheetah#168]
Hello,

I am trying to modify the targets file in the `$(LocalAppData)\Microsoft\MSBuild\SlowCheetah\v2.5.10\` directory in order to prevent the "node_modules" folder from being copied over to this directory during the build task.

`node_modules` is a directory containing packages that often have many sub-directories. It is generated by a package manager. This means it often has file paths which contain more than 260 characters, thus failing during the build task and stopping it from continuing.

Any assistance would be gratefully appreciated as I have had no luck putting in a condition so far.

I tried this, in various places, but no luck - I don't really know much at this point about MSBuild: 

`Condition="!$([System.Text.RegularExpressions.Regex]::IsMatch('%(FullPath)', 'node_modules'))"`

Using the 2.5.11 version of the VS2013 extension.

Thanks.

(Technically, this folder is excluded from my solution, so it would have been better if excluded files did not get copied, but I assume that this isn't possible as you guys are probably just copying the whole solution directory?)

**Comment by sayedihashimi** [comment]
Did you get this figured out?

**Comment by ashclarke** [comment]
Yes I did, but not with the existing setup.

I deleted the slow cheetah version folders in `%APPDATA%`. Uninstalled the extension and removed traces from the web.config.

I reinstalled, via nuget, which updated the web config entries. I then reinstalled the extension.

Since doing that it hasn't thrown me any errors, so I believe it is fixed.
