### ISSUE TITLE
SlowCheetah Does not Transform App.config in my Test Projects during release build

### ISSUE THREAD

**Issue by mani0070** [sayedihashimi/slow-cheetah#172]
I have spend hours of install , uninstall follow the instruction etc nothing worked for me..#

1. Installed the Nuget package using package manager console
2. Added Transfrom
3. Updated the entries
4. Did a release build
5. checked the config in the \bin directory . No transforms made.

**Comment by sayedihashimi** [comment]
What version of Visual Studio? And was it any specific type of test project?

**Comment by mani0070** [comment]
Visual studio 2010 and its a Test Project

**Comment by mani0070** [comment]
Update : I tried the same steps above, it works on some other test projects in the same solution. I'm confused. your help will be much appreciated here

**Comment by sayedihashimi** [comment]
Can u share the solution?

**Comment by mani0070** [comment]
I can do a screen share, Is there anything specific to look for?

**Comment by sayedihashimi** [comment]
I'm in vacation so can't commit to any specific times. Thats not the best way to diagnose this either. I either need steps to reproduce or a solution which shows the error to diagnose locally.

**Comment by mani0070** [comment]
I dont know how to reproduce the error other than that one project

**Comment by sayedihashimi** [comment]
Ok once you have steps to reproduce or are able to share the solution then I'll investigate. Until then there is nothing I can do.

**Comment by mani0070** [comment]
Thanks for your time. I have moved on to use powershell scripts. Which works better now. If I get any more bandwidth I will take a look.

**Comment by sayedihashimi** [comment]
Ok thanks closing
