### ISSUE TITLE
vs2015: Pass null instead of All to InstallPackage

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/slow-cheetah#173]
For the line https://github.com/sayedihashimi/slow-cheetah/blob/52c0e7c9f7c0b10d536d5e328e05f51b1cbba8d7/SlowCheetah/SlowCheetahPackage.cs#L1037

We should pass null instead of "All".

Note: this is required for VS2015 as it may not have the "All" option (it's not there today at least)

cc @WillBuik

**Comment by davilimap** [comment]
VS extension no longer installs NuGet package. #209 tracks this feature in future versions.
