### ISSUE TITLE
 New issue TransformXml task could not be loaded from SlowCheetah.Xdt.dll

### ISSUE THREAD

**Issue by ankurjasoria** [sayedihashimi/slow-cheetah#175]
I am uploading my code on our PreLive Enviourment but we have an error I sharing you build log also please check and verify where exactly issue occur ?

Log - 
Copying file from "app.config" to "obj\PreLive\Fareportal.NoteService.Core.csproj-sc.App.config".
C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteService.Core\Properties\SlowCheetah\SlowCheetah.Transforms.targets(160,5): error MSB4062: The "TransformXml" task could not be loaded from the assembly C:\Release_Team\MKT_GIT\CRM\packages\SlowCheetah.2.5.14\tools\SlowCheetah.Xdt.dll. Could not load file or assembly 'file:///C:\Release_Team\MKT_GIT\CRM\packages\SlowCheetah.2.5.14\tools\SlowCheetah.Xdt.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteService.Core\Fareportal.NoteService.Core.csproj]
Done Building Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteService.Core\Fareportal.NoteService.Core.csproj" (default targets) -- FAILED.
Done Building Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\Libraries\MongoRepository\MongoRepository.Net45.csproj" (default targets) -- FAILED.
Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\Web\Fareportal.NoteService.WebAPI.csproj" (1) is building "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteServices\NoteLinkingService\Fareportal.NoteService.NoteLinking.csproj" (6:2) on node 1 (default targets).
RestorePackages:
  ".....nuget\NuGet.exe" install "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteServices\NoteLinkingService\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "....\ "
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
Done Building Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteServices\NoteLinkingService\Fareportal.NoteService.NoteLinking.csproj" (default targets) -- FAILED.
Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\Web\Fareportal.NoteService.WebAPI.csproj" (1) is building "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteServices\VanilaNoteService\Fareportal.NoteService.Default.csproj" (7:2) on node 1 (default targets).
RestorePackages:
  ".....nuget\NuGet.exe" install "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteServices\VanilaNoteService\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "....\ "
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
Done Building Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteServices\VanilaNoteService\Fareportal.NoteService.Default.csproj" (default targets) -- FAILED.
Done Building Project "C:\Release_Team\MKT_GIT\CRM\NoteSvc1\Web\Fareportal.NoteService.WebAPI.csproj" (Clean;Rebuild target(s)) -- FAILED.

Build FAILED.

"C:\Release_Team\MKT_GIT\CRM\NoteSvc1\Web\Fareportal.NoteService.WebAPI.csproj" (Clean;Rebuild target) (1) ->
"C:\Release_Team\MKT_GIT\CRM\NoteSvc1\Libraries\MongoRepository\MongoRepository.Net45.csproj" (default target) (4:4) ->
"C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteService.Core\Fareportal.NoteService.Core.csproj" (default target) (5:5) ->
(TransformAllFiles target) -> 
  C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteService.Core\Properties\SlowCheetah\SlowCheetah.Transforms.targets(160,5): error MSB4062: The "TransformXml" task could not be loaded from the assembly C:\Release_Team\MKT_GIT\CRM\packages\SlowCheetah.2.5.14\tools\SlowCheetah.Xdt.dll. Could not load file or assembly 'file:///C:\Release_Team\MKT_GIT\CRM\packages\SlowCheetah.2.5.14\tools\SlowCheetah.Xdt.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Release_Team\MKT_GIT\CRM\NoteSvc1\NoteService.Core\Fareportal.NoteService.Core.csproj]

**Comment by davilimap** [comment]
As of 2.5.48, all of the assemblies are handled by NuGet on downloading or restoring the package. Try updating (see [here](https://github.com/sayedihashimi/slow-cheetah/blob/master/doc/update.md) and seeing if the issue persists
