### ISSUE TITLE
How to exclude transformed file in APP_DATA from published package while using slow cheetah

### ISSUE THREAD

**Issue by roopkt** [sayedihashimi/slow-cheetah#176]
http://stackoverflow.com/questions/31593306/how-to-exclude-transformed-file-in-app-data-from-published-package-while-using-s

Hi,
Is there anyway while doing publish the web application package and put the transformed file in different folder? 

I have 2 requirement one is while deploying to server using MSDeploy I want the transformed file to be present in APP_DATA. However, while creating package (zip file) using publish profile I want the transformed file to be not present in APP_DATA rather I want to put it in some other folder. Is it possible ?

Is it possible to transform file and put it in different folder location ?

**Comment by davilimap** [comment]
SlowCheetah only transforms files and puts them in their appropriate output folders. If you want a file to be placed in different places depending on the publish that you are doing, that depends on your project type and publish configurations.
