### ISSUE TITLE
VSO - VS2015 - Not transforming

### ISSUE THREAD

**Issue by hermesramos** [sayedihashimi/slow-cheetah#177]
It just does not work. 

Also, if you use VS 2015, to run unit tests under VSO, you have to set VS 2013. If you set 2015, it will not work.

Microsoft always realising crapware. Always buggy. It is the same history for decades.

**Comment by sayedihashimi** [comment]
Adding @willbuik

**Comment by ronnotel** [comment]
Not sure if this is the same issue but after installing 2.5.15 on a new installation of VS2013 & VS2015 I'm not seeing the "Transform" menu item appear when I right-click on App.config in a new project. Any help on debugging this would be much appreciated.

**Comment by sayedihashimi** [comment]
Did you install the nuget package or the visual studio extension? The extension is required for the menu option.

**Comment by ronnotel** [comment]
You rock - thanks.

Btw, this little piece of code is the most useful extension by far in VS universe. Thanks for your perseverance. Do me a solid and shoot me a link to your tip jar if you have one.

**Comment by WillBuik** [comment]
@hermesramos Can you expand on the issue a bit?  What exactly isn't getting transformed?
