### ISSUE TITLE
Post SlowCheetah (2015) install, web.config no longer copied after publish

### ISSUE THREAD

**Issue by JamesSkemp** [sayedihashimi/slow-cheetah#178]
I've recently installed the SlowCheetah extension and enabled it for a Visual Studio 2015 web project.

After creating transforms for a ConnectionStrings.config I found that a publish correctly applied the transforms.

However, the standard Web.config was no longer getting published/overwriting the published copy.

Publish method is File System, with all versions saving to the same local directory. Files are not being deleted prior to publish. If I delete the web.config in the publish directory and publish, it is copied over.

Testing on another machine, with code prior to my SlowCheetah install, works just fine (published web.config is transformed/updated correctly). They had installed the SlowCheetah extension, but did not transform any files in the project with it.

I removed the SlowCheetah package, then removed the SlowCheetah extension, but the web.config still isn't transformed.

Any ideas?

**Comment by sayedihashimi** [comment]
web.config transform is handles by the Web project itself. Are you saying that adding SlowCheetah causes that to stop working or is the issue with ConStrings.xml?

**Comment by JamesSkemp** [comment]
The first, that after installing SlowCheetah Web.config transforms appear to be impacted.

This doesn't appear to be because of the extension, because the publish still worked for a co-worker that installed the extension. He had not installed the NuGet package/updated the web project (.proj) file though.

ConnectionStrings.config transforms as expected.

**Comment by BenAlabaster** [comment]
I noticed that web.config no longer gets published in the case that its build action is set to None (which is as you might expect), but if you change it to Content, it works again.

**Comment by davilimap** [comment]
As @BenAlabaster suggested, try changing the build action of web.config to None. Also, try updating to the latest version of SlowCheetah (see [here](https://github.com/sayedihashimi/slow-cheetah/blob/master/doc/update.md)) and verifying if the issue still exists
