### ISSUE TITLE
Slowcheetah.Transforms.targets pathing 

### ISSUE THREAD

**Issue by ShaneCourtrille** [sayedihashimi/slow-cheetah#181]
Hello,

When we install SlowCheetah 2.5.14/2.5.15 we find this..

    <sc-MSBuildLibPathLocal Condition=" '$(sc-MSBuildLibPathLocal)'=='' ">$(LocalAppData)\Microsoft\MSBuild\SlowCheetah\v2.5.11\</sc-MSBuildLibPathLocal>

Just wondering if the 2.5.11 is okay?

**Comment by sayedihashimi** [comment]
Are you having an issue with this? When the nuget package is used that value is ignored, and the package should be getting installed/used.

**Comment by ShaneCourtrille** [comment]
We are having an issue with Slow Cheetah not working for VS2015 or VSO Team Builds with the VS2015 setting for our NLog.config file.  I do notice that the 11 does get used on the server as .14 gets copied into the /11/ folder.  Our web.config works fine though so I doubt it's the cause and I'll create another issue for it after a little more debugging.

**Comment by sayedihashimi** [comment]
So should we close this?

**Comment by sayedihashimi** [comment]
Closing since this seems resolved
