### ISSUE TITLE
Not transforming NLog.config file in Azure Web Cloud Project post VS2015

### ISSUE THREAD

**Issue by ShaneCourtrille** [sayedihashimi/slow-cheetah#182]
We've been using SlowCheetah for awhile now with a lot of success.  We recently switched over to VS 2015 and moved from a VS Online hosted XAML Build to a Team Build one.  Now we're seeing that our web.config files are still being transformed properly but our NLog.config is not.  

Version: 2.5.15
Project is a an ASP.Net MVC web site which gets deployed to Azure so we have an Azure Cloud Service project.  When create a Package from my Azure Cloud Service project I see the following in the logs:

7>Task "SlowCheetah.Xdt.TransformXml" (TaskId:112)
7>  Task Parameter:Source=C:\data\tfs\EDM\Development\Source\EDM\EDM Site\NLog.config
7>                  IsAppConfig=false
7>                  Link=
7>                  OriginalItemSpec=NLog.config
7>                  SubType=Designer
7>                  TransformOnBuild=true (TaskId:112)
7>  Task Parameter:Transform=NLog.Release - STG.config (TaskId:112)
7>  Task Parameter:Destination=bin\NLog.config
7>                  IsAppConfig=false
7>                  Link=
7>                  OriginalItemSpec=NLog.config
7>                  SubType=Designer
7>                  TransformOnBuild=true (TaskId:112)
7>  Transfroming source file: C:\data\tfs\EDM\Development\Source\EDM\EDM Site\NLog.config (TaskId:112)
7>  Applying Transform File: NLog.Release - STG.config (TaskId:112)
7>  Output File: bin\NLog.config (TaskId:112)
7>Done executing task "SlowCheetah.Xdt.TransformXml". (TaskId:112)

I found the NLog.config in the bin and it's correct but when I open the package the NLog.config it contains is actually the original one so it looks like the Output File path isn't correct for this kind of project.

**Comment by sayedihashimi** [comment]
It sounds like a regression with cloud project build system. I'd file a bug with MSFT. In either case @willbuik is the new maintainer I'll let him chime in with his thoughts

**Comment by ShaneCourtrille** [comment]
What about the -sc stuff being done to the web/app.config? Is that just so you can re-use that version as an input for the build system which then puts it into the right place?

**Comment by sayedihashimi** [comment]
@ShaneCourtrille 
>What about the -sc stuff being done to the web/app.config?

What do you mean? Sorry I'm not following the question.

**Comment by ShaneCourtrille** [comment]
The SlowCheetah .targets file does some work with the web.config and adds an -sc to it.  I'm wondering if this is why the app.config would still work or if that's just a helper that doesn't actually change the normal process.

**Comment by sayedihashimi** [comment]
@ShaneCourtrille SlowCheetah doesn't transform web.config. That's built into web projects during publish.

SlowCheetah will transform app.config and create a -sc file but the C#/VB build process will pickup the right file and copy it to `<appname>.exe.config`. There shouldn't be any web.config file with -sc as far as I know.

**Comment by ShaneCourtrille** [comment]
Ahhh.. we have an app.config for a worker role project which explains why I saw that.  Okay ignore that comment then.  We did end up switching our config into web.config and it's transforming properly now but that's definitely not a great solution.

**Comment by altafub** [comment]
I am facing the same issue where the files are not getting transformed for Azure Cloud Service project and VSO with on prem Build Agent Pool.

They however work fine with Web Project + Azure Web App + VSO with on prem Build Agent Pool.

**Comment by davilimap** [comment]
Can you try updating to the newest version of SlowCheetah (see [this](https://github.com/sayedihashimi/slow-cheetah/blob/master/doc/update.md)) and see if the issue persists?

**Comment by davilimap** [comment]
Should be fixed with the newest version. If not, reopen the issue.
