### ISSUE TITLE
SlowCheetah not transforming because of misplaced PropertyGroup

### ISSUE THREAD

**Issue by alrhr** [sayedihashimi/slow-cheetah#183]
After Updating from Visual Studio 2013 to 2015 the transformation of app.config files failed. Interesting ly enough "Preview Transform" showed the expected (transformed) result. This could be fixed by copying the misplaced "SlowCheetah"-PropertyGroup (see below) from the end of the Visual Studio project file (csproj) to a location before the first ItemGroup at the beginning of the file.

``````
<PropertyGroup Label="SlowCheetah">
    <SlowCheetahToolsPath>$([System.IO.Path]::GetFullPath( $(MSBuildProjectDirectory)\..\packages\SlowCheetah.2.5.15\tools\))</SlowCheetahToolsPath>
    <SlowCheetah_EnableImportFromNuGet Condition=" '$(SlowCheetah_EnableImportFromNuGet)'=='' ">true</SlowCheetah_EnableImportFromNuGet>
    <SlowCheetah_NuGetImportPath Condition=" '$(SlowCheetah_NuGetImportPath)'=='' ">$([System.IO.Path]::GetFullPath( $(MSBuildProjectDirectory)\Properties\SlowCheetah\SlowCheetah.Transforms.targets ))</SlowCheetah_NuGetImportPath>
    <SlowCheetahTargets Condition=" '$(SlowCheetah_EnableImportFromNuGet)'=='true' and Exists('$(SlowCheetah_NuGetImportPath)') ">$(SlowCheetah_NuGetImportPath)</SlowCheetahTargets>
</PropertyGroup>```
``````

**Comment by mikanyg** [comment]
I had the same issue in VS2015, but occured when I upgraded from version 2.5.10.3 to 2.5.15.
I solved it by moving the SlowCheetah property group like described above.

**Comment by mulder999** [comment]
Add similar issue with 2.5.15 in VS2013 with a C# project. I add to creating manually the SlowCheetah <PropertyGroup> and <Import> nodes. I have not seen yet such issue with 2.5.15 in VS2013 for VB projects, nodes were created automatically.

**Comment by sayedihashimi** [comment]
@willbuik owns 2.5.15+. Will, any update?

**Comment by z32jxs** [comment]
I was experiencing the same issue with version 2.5.15 and VS2013. After moving up the Property Group the transformations started working.

**Comment by Kaelum** [comment]
Ditto, however I never upgraded my VS2013 installation.  After installing VS2015 (side-by-side) and 2.5.15 for VS2015, it also upgraded VS2013.  Once that happened, every project in VS2013 that I opened with a version prior to 2.5.15, upgraded to 2.5.15 and moved the <PropertyGroup> to the end of the .proj file.  Removing SlowCheetah from the solution, and then adding it back, puts the <PropertyGroup> at the end of the file as well, which will never work.

**Comment by davilimap** [comment]
As of 2.5.48, SlowCheetah no longer uses this property group, instead relying on NuGet to place the correct import.
