### ISSUE TITLE
Access denied with web.config transform in VS2015 & slow cheetah beta

### ISSUE THREAD

**Issue by katpurz** [sayedihashimi/slow-cheetah#184]
We have an ASP.NET application running in VS2015 using the Slow Cheetah beta... all works fine locally, but when I add a build definition for our buildserver, it's erroring out on the transform step with:

C:\Builds\DATC\Service\Service\Service.csproj (240): Could not write Destination file: Access to the path 'C:\Builds\DATC\Service\Service\Web.config' is denied.

(denied due to it being READ ONLY when it's copied over to build server, I'm guessing)

Is there a known work around for this?  thanks much in advance!

**Comment by sayedihashimi** [comment]
SlowCheetah doesn't transfor web.config files. That's built into web projects when publishing.
