### ISSUE TITLE
Use with TeamCity

### ISSUE THREAD

**Issue by ayseff** [sayedihashimi/slow-cheetah#185]
How do I use Slow-Cheetah with TeamCity?  According to http://www.hanselman.com/blog/SlowCheetahWebconfigTransformationSyntaxNowGeneralizedForAnyXMLConfigurationFile.aspx, I can simply commit the Slow-Cheetah files to source.  Accordingly, I put this line in the beginning of my .csproj file:
`<Import Project="..\..\Dependencies\SlowCheetah\v2.5.11\SlowCheetah.Transforms.targets"  />`

Yet, TeamCity is not transforming.  ("Preview Transform" in Visual Studio is working fine.)

Can you please assist?

Thanks,

**Comment by urbanhusky** [comment]
Have you tried adding the SlowCheetah nuget package, which should contain everything that is needed to build with msbuild etc.?

**Comment by davilimap** [comment]
As @urbanhusky said, you need to download the NuGet package for it to transform on build. The updated NuGet package will be released soon
