### ISSUE TITLE
Add Transform option not available after installing Slowcheetah 2.5.15 / VS2015 Update 1

### ISSUE THREAD

**Issue by rschaeferhig** [sayedihashimi/slow-cheetah#189]
I have a Console app Solution in VS 2015 Update 1. I installed Slowcheetah 2.5.15 via the Manage NuGet Packages for Solution dialog. The Slowcheetah updates to the Project file are there, the targets file is in Properties/Slowcheetah and Slowcheetah is in the Packages folder. 

When I right-click on app.config I don't get the Add Transform option. How do I debug this?

**Comment by todthomson** [comment]
Generally you need this to get `Add Transform` https://visualstudiogallery.msdn.microsoft.com/69023d00-a4f9-4a34-a6cd-7e854ba318b5 that being said I don't think SlowCheetah supports 2015.

**Comment by rschaeferhig** [comment]
The second link did it. The first one only installs in 2013. The entry at the second link says it's the SlowCheetah for VS2015 "Preview". I guess we need a response from Sayed or whoever is now maintaining SlowCheetah (Bueller?) as to it's future.

**Comment by sayedihashimi** [comment]
I am no longer maintaining this. According to the reply at https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2043217-support-web-config-style-transforms-on-any-file-in @WillBuik is the new owner. In the reply he states.

>Our long term plan, however, is to integrate this functionality into a future version of Visual Studio.

So I would expect that this functionality will be baked in at some point.

Another note, SlowCheetah was modified by @WillBuik and released as version `2.5.15`. I don't have the code for that version and didn't find it when I looked on github.

**Comment by rschaeferhig** [comment]
Thanks Sayed.

**Comment by davilimap** [comment]
As of 2.5.38, SlowCheetah supports VS 2015 and 2017, just download the extension [here](https://marketplace.visualstudio.com/items?itemName=WillBuikMSFT.SlowCheetah-XMLTransforms) to have access to the Add and Preview Transform options.

**Comment by rschaeferhig** [comment]
Thanks! I read somewhere that MS was finally going to build this into Visual Studio. I thought maybe 2017 but so far not. Have you heard anything?
