### ISSUE TITLE
Azure Webjob seems to build and deploy Debug and not Release config

### ISSUE THREAD

**Issue by jeffmang** [sayedihashimi/slow-cheetah#191]
I have an Azure webjob project (which is really just a C# console application with an app.config) Using Slow Cheetah, I can see the App.Debug.config and App.Release.config files.  I can right click on the App.Release.config and choose the preview transform menu item and see that config file is built properly.  However when I go to the bin/release folder the debug version of the App.config file is present.   Also when I deploy the job to Azure the config is the debug version.  I am able to manually change the config on Azure using Filezilla, but it is a pain.

**Comment by sayedihashimi** [comment]
Sounds like a bug in Webjobs publishing. Let's see what @mlorbetske says.

**Comment by mlorbetske** [comment]
I'm a little unclear on what's happening here - are you saying that the debug transform is being run and the resulting app.config is published or that no transform is being run? Also, are you publishing the WebJob via publish on the console app or via a web app project with the WebJob associated to it?

**Comment by sayedihashimi** [comment]
@mlorbetske for a console app you can use SlowCheetah to transform the `app.config` file during the build process. This is conceptually similar to the "environment" support we have in .NET Core projects. The transformation happens with a well known MSBuild pattern. My guess is that the webjobs code is not picking up the artifacts correctly, or not invoking the build in a way that prevents the transforms from kicking off.

If SlowCheetah is not working with webjobs projects then it's also likely that users will have issues using the [Microsoft.Bcl.Build](https://www.nuget.org/packages/Microsoft.Bcl.Build/) NuGet package. The BCL targets transforms the app.config in the same way that SlowCheetah does.

**Comment by jeffmang** [comment]
mlorbetske,  I don't think any transform is being run.  just the contents of what are in the App.config are ending up for both debug and release.   I am publishing the webjob in the solution explorer by right clicking on the webjob project and choosing Publish as Aszure Webjob...  (the output type of the webjob is a console appliction)

**Comment by davilimap** [comment]
I tried this with the new version (2.5.48) and the transforms are working correctly on publish. I created a new Auzre WebJob project and added transforms. Upon publishing to a local folder, the transforms are correct
Can you try with the new version and see if the issue persists? If so, provide instructions to reproduce it from a new project.
