### ISSUE TITLE
SlowCheetah.Transforms.targets and packages.config included in publish output of web projects

### ISSUE THREAD

**Issue by BenAlabaster** [sayedihashimi/slow-cheetah#192]
During NuGet installation of SlowCheetah in web projects, the targets and packages.config files are added to the project with the Build Action "Content" instead of "None" which causes them to be published in the build output.

Workaround: Change the ItemType to None for these files which causes them not to be included in the build output.

Fix Acceptance Criteria: When these files are added to web projects with an existing packages.config and/or SlowCheetah.Transforms.targets file, the existing build action should be honoured, if they are to be added by this installation, they should be added with the Build Action "None"

For example:

```
<ItemGroup>
    <None Include="properties\SlowCheetah\SlowCheetah.Transforms.targets" />
</ItemGroup>
```

packages.config appears to be a NuGet bug unrelated to (but affecting) SlowCheetah

Pull request issued to fix build action of SlowCheetah targets: https://github.com/sayedihashimi/slow-cheetah/pull/193

**Comment by davilimap** [comment]
The update to SlowCheetah removes the need for the `SlowCheetah.Transforms.targets` file in the properties folder.
The `packages.config` file is now handled by the NuGet package manager so it should be added as None.
