### ISSUE TITLE
Add Transform not adding config for custom build configuration

### ISSUE THREAD

**Issue by lamontadams** [sayedihashimi/slow-cheetah#197]
Hi,

I have a VS 2015 Console project with three build configurations: Debug, Release (both standard) and UAT (copied from Release). After installing "Slow Cheetah XML Transforms Preview for 2015," the "Add Transform" context menu creates app.Debug.config and app.Release.config, but nothing for the UAT configuration. 

How can I add a transform for the UAT configuration?

**Comment by davilimap** [comment]
I have tried  this with the new version (2.5.48) and the transforms are being added correctly. 
If you are still experiencing this after updating, reopen the issue and add steps to reproduce this with a new project.
