### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by xperiandri** [sayedihashimi/slow-cheetah#198]
As I understand this tool is as simple as possible, isn't it?
Just install package and every publish it transforms, correct?

So I installed it into ASP.NET Core project into dependencies section.
But nothing happens on publish.

**Comment by davilimap** [comment]
Can you clarify some of the steps you have taken and what you would like the end result to be? I.E. what file you are trying to transform, what transformations you added, etc.

Web.config transformations are not supported by SlowCheetah yet, but .NET framework projects should have those set up on publish. .NET Core projects are a bit different as the framework is still in its first iterations and may not support Web.config trasformations.

**Comment by xperiandri** [comment]
Well I had an ASP.NET Core project and created such transform
<img width="1080" alt="slowcheetah" src="https://cloud.githubusercontent.com/assets/2365592/23723089/801ac2ba-0450-11e7-8436-d4867f7309d5.png">
I wanted it to be transformed when I publish to `Staging.pubxml` but transform does not happen.
