### ISSUE TITLE
MSBuild  Transforms (XDT transform fails on > in source attribute)

### ISSUE THREAD

**Issue by ligaz** [sayedihashimi/slow-cheetah#20]
I have a MSBuild file that contains a couple of [MSBuild transformations](http://msdn.microsoft.com/en-us/library/ms171476.aspx). I want to transform this file with an XML transformation, but the problem is that the transformation fails, because an attribute value contains a greater than symbol **>** (coming from the MSBuild transformation **->**). Also the thrown exception is ambiguous: _System.UriFormatException: Invalid URI_. If I XML encode the symbol everything works - but it should work out of the box in the first place.

Do you plan to open-source the code for the MSBuild tasks as well (SlowCheetah.Tasks.dll)?

**Comment by davilimap** [comment]
The underlying bug on XDT is fixed, so this is also fixed. If the problem still exists, reopen the issue.
