### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by cilerler** [sayedihashimi/slow-cheetah#201]
Please update the extension to support Visual Studio 2017

**Comment by trekco** [comment]
+1

please

**Comment by sayedihashimi** [comment]
Adding @jviau

**Comment by jviau** [comment]
SlowCheetah [v2.5.48](https://github.com/sayedihashimi/slow-cheetah/releases/tag/v2.5.48) has been published to both NuGet and Visual Studio gallery.
