### ISSUE TITLE
Add Transform would throw memory exception

### ISSUE THREAD

**Issue by GiridharanNair** [sayedihashimi/slow-cheetah#210]
It is a VB.Net Project on .Net Framework 4.0. On click of Add Transform in app.config the following exception gets thrown as shown in the attachment.

![image](https://cloud.githubusercontent.com/assets/22915855/22750662/44f564ac-edf7-11e6-9723-0058667af76d.png)

**Comment by davilimap** [comment]
Try updating to the newest version of SlowCheetah and verifying if the issue persists. If it does, can you give me specific steps to reproduce it from a new project?

**Comment by davilimap** [comment]
If the problem persists, reopen the issue with steps to reproduce it from a new project or the files from the project that caused the error.
