### ISSUE TITLE
Doesn't work in WPF

### ISSUE THREAD

**Issue by haldiggs** [sayedihashimi/slow-cheetah#222]
After I couldn't make it work in my own WPF application I downloaded the SlowCheetah.Samples and tried the WPF there as well. Still did not work. Sure did love the idea though

**Comment by davilimap** [comment]
Sorry, but the sample projects haven't been updated for the newest version of SlowCheetah. I've opened #223 to monitor this.
I tried creating a new WPF app and transformations seem to be working properly. Can you give more information on your issue such as steps to repro it or a project of yours that doesn't execute the tranforms properly.

**Comment by haldiggs** [comment]
then it must be something I did wrong in the installation, it was a little confusing on my end. will work on it.
