### ISSUE TITLE
Transforms don't apply during build in Visual Studio 2015

### ISSUE THREAD

**Issue by DanMayor** [sayedihashimi/slow-cheetah#229]
Using visual studio 2015, we can preview the merged transforms but they do not actually apply to the webapp.dll.config xml file during the build.

Low priority, I was able to work around the issue (using other technologies) but others who wish to use Slow Cheetah in Visual Studio 2015 will likely need this issue resolved.

**Comment by davilimap** [comment]
Hi, in order for the transforms to be executed on build, you need the SlowCheetah NuGet package installed to your project.
If the package is already installed on your project and transforms still aren't executed, can you provide more information on the project type, the configurations you're using, etc? Steps to repro the issue would be the most helpful.

**Comment by DanMayor** [comment]
https://github.com/DanMayor/SP.Blog

Was trying to use Slow Cheetah in this project. There is a file "Web.Custom.config" that is not in the Github project. (It contains credentials).

The project as of now has Slow Cheetah removed, however at the time when testing i was having problems using Visual Studio 2015, did have the extension and the nuget package installed at the time. No error messages or warnings, just wasn't actually applying "Web.Custom.config" when in the custom configuration. Also tested with Debug configuration, Slow Cheetah was not merging the Web.Debug.config into the output SPBlog.dll.config file.

**Comment by crispy-b99** [comment]
I am having the same problem in VS 2015. Preview works but build is not updating the web/app config file. I have two projects with the same issue.

Project file attached....
Ma1sy001
[DigitalPortals.VenueService - Copy.csproj.txt](https://github.com/sayedihashimi/slow-cheetah/files/805788/DigitalPortals.VenueService.-.Copy.csproj.txt)

**Comment by davilimap** [comment]
Currently SlowCheetah does not support build-time configurations for web.config files. Web projects have native transformations on publish, but we plan to support build transformations with SlowCheetah.
I'll close this issue since it's already been reported in #39 that issue should be updated accordingly.
