### ISSUE TITLE
"Add Transform" not appearing in VS2015

### ISSUE THREAD

**Issue by rfg76** [sayedihashimi/slow-cheetah#232]
I've installed the package vía NuGet. I haven't had previous versions installed.
However the option menu to add transform is not appearing.
I have tried with a  Console project and a Windows Service project
Any hints?

**Comment by sayedihashimi** [comment]
The NuGet package contains the logic to run transforms. The UI for Add Transform is in the SlowCheetah Visual Studio extension.

**Comment by davilimap** [comment]
As @sayedihashimi said, you do need the [SlowCheetah extension](https://marketplace.visualstudio.com/items?itemName=WillBuikMSFT.SlowCheetah-XMLTransforms) for this. @rfg76 if you do have it installed, can you explain more about how you arrived at the problem?

**Comment by rfg76** [comment]
Ok, I installed the extension and now everything works fine. I was confused.
