### ISSUE TITLE
Reminding me of wrong version

### ISSUE THREAD

**Issue by pecen** [sayedihashimi/slow-cheetah#238]
Hi,

After install, in Visual Studio 2015, if I do a transform a yellow row just below the menu row appears saying that it looks like I have the wrong version installed, and no transforms will take place (although it does). I have checked that I have the latest version, I have uninstalled, and re-installed again, but I still get the error. 

Regards,
Peter

**Comment by davilimap** [comment]
Hi Peter. It may be that you were using an older version of SlowCheetah that altered your project file. [This document](https://github.com/sayedihashimi/slow-cheetah/blob/master/doc/update.md) explains how to remove these imports so they don't potentially alter your transformation or your build process.
You can also wait for the next version of SlowCheetah which performs this fix automatically.
If you find that none of this applies to your project, reopen the issue and give steps to reproduce it from a new project.

**Comment by pecen** [comment]
Hi,
Thanks for your answer. 
First of all, I have never used SlowCheetah before at all, so I don't understand how those rows could have ended up in any of the project files of my solution. Secondly, I installed SlowCheetah through download of a .vsix file from the SlowCheetah site, which means it pops up as a context menu item when right-clicking on a config file (app, nhibernate, web etc) and gives you the menu choice "Add Transformation". Thirdly, we have like 120 projects in our solution which will make it a bit tedious, or rather hard, to go through all the .csproj files. 
BR,
Peter

**Comment by davilimap** [comment]
Thanks for the additional info. If you have never used SlowCheetah, someone on your team most likely used a previous version of it on one other projects and it left behind some imports. If you're unable to identify exactly which project has these old lines, just wait for the next version of SlowCheetah which should be out soon.
