### ISSUE TITLE
Warning that I  do not have correct version of SlowCheetah  nuget package installed

### ISSUE THREAD

**Issue by MNF** [sayedihashimi/slow-cheetah#241]
I've added SlowCheatah extension as latest version from https://marketplace.visualstudio.com/items?itemName=WillBuikMSFT.SlowCheetah-XMLTransforms
When tried to use it, Visual Studio showed message "that I do not have correct version of SlowCheetah  nuget package installed" and linked to https://github.com/sayedihashimi/slow-cheetah/blob/master/doc/update.md
I was confused.
It's not clear why I need to update nuget package if I just installed the latest extension.
Do  I need to install both extension and nuget package?
If you can't include package installation as a part of Add transform, please include notice that we need both at the top of the documentation update.md.

**Comment by davilimap** [comment]
Installation for the NuGet package and migration from older versions was tracked in #209 and has been fixed for the next release.
In regards to the documentation, that is being worked on at the moment. Thanks for the feedback, we'll make sure to address the Extension vs NuGet logic so it's clearer to users.
