### ISSUE TITLE
Compilation error: src\Zen.Databases.DbUp\Zen.Databases.Db.csproj  in teamcity

### ISSUE THREAD

**Issue by nnikhilnn** [sayedihashimi/slow-cheetah#247]
![error](https://cloud.githubusercontent.com/assets/28543151/25820948/c022a472-33f8-11e7-803e-57e29f18b16e.JPG)

when i was trying to run a build i encountered with dis above  error
 
![git](https://cloud.githubusercontent.com/assets/28543151/25821019/0aace264-33f9-11e7-9422-26b5b4bd89d8.JPG)

can anyone help me with this error?

**Comment by davilimap** [comment]
This issue doesn't seem to be related to SlowCheetah

**Comment by sayedihashimi** [comment]
It looks like you're not authorized to push the package to nuget.org. See https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#push, I think you'll need to pass ApiKey or username/password.
