### ISSUE TITLE
'Preview Transform' does nothing when selected.

### ISSUE THREAD

**Issue by MrClyfar** [sayedihashimi/slow-cheetah#249]
**System Info**
Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.15) Release
VisualStudio.15.Release/15.2.0+26430.15
Microsoft .NET Framework
Version 4.7.02046

SlowCheetah extension installed v3.0.61.18192

**Symptoms**
When selecting the menu option 'Preview Transform', against a config transform file in my project, nothing happens. No code diff window appears, no error message is shown. It silently fails.

Is there a source where exceptions thrown by Slowcheetah are stored?

**Comment by xantari** [comment]
Same issue here. VS 2015, latest SlowCheetah.

**Comment by davilimap** [comment]
This repo is deprecated. Please see [here](https://github.com/Microsoft/slow-cheetah/issues) for current issues being tracked.
