### ISSUE TITLE
Add an IDE option to not modify the project file when using Add Transform context menu.

### ISSUE THREAD

**Issue by kennethito** [sayedihashimi/slow-cheetah#33]
Just a suggestion.

I have a team project which is using the CustomAfterMicrosoftCommonTargets to add the SlowCheetah targets into all output projects from source control.

Everytime I use the right click context menu to add a transform, the slow cheetah extension tries to modify the project file and add the local version of the script.

**Comment by davilimap** [comment]
The SlowCheetah extension no longer modifies the project file. All target files are handled by the NuGet package.
