### ISSUE TITLE
Transforms are not going into output dir for referenced projects

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/slow-cheetah#34]
If you have the following setup:
1. ClassLibraryA has foo.xml
1. foo.xml has transforms configured
1. ClassLibraryB references ClassLibraryA
1. Build

The transformed foo.xml does not make it to the output folder for ClassLibraryA, it should.

**Comment by jarlelin** [comment]
I have other .config files beside the app.config in my projectA that I would like included in the output folder of projectB where projectB is the one that I'm building and projectB references projectA.

This method includes the app.config files as projectA.dll.config, but I would like for a larger set of transormed files from one specific project to be included in the final output.

Is there any support for this at all currently?
