### ISSUE TITLE
TransformXml.Execute may hide root cause XmlException

### ISSUE THREAD

**Issue by chriseldredge** [sayedihashimi/slow-cheetah#45]
Using SlowCheetah.Tasks 1.0.10727.0, if an XmlException is thrown in TransformXml.Execute, the catch block will try to parse a URI from the exception instance's Source property. When that property is blank, a UriFormatException is thrown.

This bug causes an unhandled exception to be thrown by the task and the finally block incorrectly reports "Transformation succeeded".

**Comment by davilimap** [comment]
With the newest version of XDT (as well as SlowCheetah), this is fixed.
