### ISSUE TITLE
Add Transform command does not show up for files named *web.config

### ISSUE THREAD

**Issue by jinglecat** [sayedihashimi/slow-cheetah#56]
If the config file name contains 'web.xxx', for example,  web.my.config, the 'Add Transform' won't show from its context menu as the following screenshot:
![SlowCleathBug](https://f.cloud.github.com/assets/2097551/15582/99e6e408-4794-11e2-93eb-c9db149f6c42.png)

**Comment by davilimap** [comment]
Closed by #211
