### ISSUE TITLE
Unable to transform files that are not 'checked out'

### ISSUE THREAD

**Issue by devAlex** [sayedihashimi/slow-cheetah#73]
After upgrading to the latest version of slow cheetah it is not possible to transform files that are not 'checked out'.

I get the following error if i try to build my projects: "Could not write Destination file: Access to the path ' ... MyConfig.config' is denied." I can only build the project if i check out the file.

This is really annoying. With the previous version the problem does not exist.

**Comment by davilimap** [comment]
Try testing with the newest version of SlowCheetah on .NET 4.5 or later. If the problem persists, reopen the issue.
