### ISSUE TITLE
Preserve whitespacing in transformed xml

### ISSUE THREAD

**Issue by ericnewton76** [sayedihashimi/slow-cheetah#80]
Is this possible?  I now its passing through an inner library, but preserving the whitespace would be nice.

(original web.config)

``` xml
<node
  attr1="asdf"
  attr2="asdf" />
```

(transformer)

``` xml
<node 
  attr1="changethis"
  attr2="changethis2"
  xdt:Transform="Replace" />
```

(actual output)

``` xml
<node attr1="changethis" attr2="changethis2" />
```

(anticipated output)

``` xml
<node
   attr1="changethis"
   attr2="changethis2" />
```

I'm hoping that its just specifying `PreserveWhitespace` somewhere

**Comment by davilimap** [comment]
This type of whitespacing is always removed, even in the native `System.Xml` reader. As it's stated [here](http://stackoverflow.com/questions/8600402/xdocument-save-preserve-white-space-inside-tags) and [here](http://stackoverflow.com/questions/24413146/preserving-whitespace-within-xml-elements-between-attributes-when-using-xslcompi), the whitespace in an XML tag is irrelevant to most readers. This being the case, XDT (the transformation lib that SC uses) also ignores this whitespace. That being said, whitespace outside of tags is preserved by default.
