### ISSUE TITLE
Support PublishProfile for desktop applications.

### ISSUE THREAD

**Issue by djeebus** [sayedihashimi/slow-cheetah#86]
I want to be able to create transforms for publish profiles so that I can transform them the same way I can transform web application config files. Basically I want the solution for issue #46 to work in desktop apps as well.

**Comment by steveculshaw** [comment]
Any chance this will get into SlowCheetah for VS2015?

**Comment by davilimap** [comment]
This should be working as of v2.5.48 (possibly earlier). Can you try it again with the new version and seeing if it persists? If so, can you give steps to reproduce the scenario?
