### ISSUE TITLE
Installing Async nuget packages breaks SlowCheetah from working correctly

### ISSUE THREAD

**Issue by jjlucsy** [sayedihashimi/slow-cheetah#87]
I installed the Async package http://nuget.org/packages/Microsoft.Bcl.Async/. If I uninstall the async package everything works again.
I noticed in my debug folder an app.config file that is properly transformed, but the Application.Exe.config is not.

**Comment by davilimap** [comment]
It seems that this issue is resolved as of v2.5.48. I created a new project, added a transformation and it worked before and after installing the latest version of the Async package (1.0.168).
Closing the issue. If it persists, reopen it with steps to reproduce it from a new project.
