### ISSUE TITLE
Transformation of resource files for Windows Store apps (*.resw) is not working

### ISSUE THREAD

**Issue by jpatte** [sayedihashimi/slow-cheetah#89]
Hi guys,

I wanted to use SlowCheetah to transform the localized resource files of my Windows 8 application... and unfortunately it doesn't seem to work. 

I have several files named Resources.resw in my project (1 for each supported language, in a dedicated folder as described [here](http://msdn.microsoft.com/en-us/library/windows/apps/xaml/Hh965329%28v=win.10%29.aspx)), and I would like to modify some resource values based on the current configuration. However when I build, deploy and run the project the default values are still used by the app.

Does anyone else face the same problem ? I have some others successfully transformed XML files in my app though, which makes me think resource files might not be supported at the moment.

Cheers,
Julien

**Comment by davilimap** [comment]
SlowCheetah does not currently support `.resx` (or .`resw`) files. If this is something people want, open a suggestion on [the uservoice page](http://slowcheetah.uservoice.com/) to see if it has enough votes.
