### ISSUE TITLE
SlowCheetah does not transform during build

### ISSUE THREAD

**Issue by FreakinWard** [sayedihashimi/slow-cheetah#91]
Slow Cheetah has worked perfectly for over a month. Now, all of the sudden, my builds are not transforming. I do have the configuration setup on multiple projects within the solution. Both projects have the associated Debug & Release configuration files associated with the parent app.config file. 

Here is an example of my transformation statement.

``` XML
<connectionStrings>
    <add name="MSSQL" connectionString="ConnectionStringHere" xdt:Transform="Replace" xdt:Locator="Match(name)"/>
  </connectionStrings>
```

After building in either Debug or Release, I am checking the (ApplicationName).exe.config file. Here, the values do not change. I have even selected the "Preview Transformation" and the preview works without failure. It seems like Slow Cheetah is not getting the call during build. 

I have uninstalled and re installed the Slow Cheetah extension. No luck.

Any recommendations on how to fix this problem?

***Update
I am able to create an entirely new project and the transforms work fine. It would appear something became corrupt or missing altogether. It seems odd that both projects would do this simultaneously.

**Comment by mani0070** [comment]
Hi Nikatdk

Can you please share where did you move the label to?

THanks,
Mani

**Comment by simonjlawson** [comment]
Confirmed, my publish profiles stopped transforming after upgrading to 4.5, the property group was moved to the bottom of the .proj, moving the <PropertyGroup Label="SlowCheetah"> section back to above the publish profiles fixes the issue.

**Comment by davilimap** [comment]
This is similar to #183 and for is closed for the same reason. All of the build logic is handled by the NuGet package.

**Comment by gurunathchoukekar** [comment]
For me app.Release.Config file was missing Appsettings open and close tags due to which transformation was not happening
