### ISSUE TITLE
NuGet Installation Fails If Project Path Contains Special Characters

### ISSUE THREAD

**Issue by nystrup** [sayedihashimi/slow-cheetah#94]
The subject line pretty much sums it up: If the fully qualified path of the project that SlowCheetah is being installed to contains reserved PowerShell characters, such as "[", the Install.ps1 script will fail.  

I haven't checked the entire script, but the first error occurs in the line:

if(!(Test-Path $projFile)){

It should, of course, read:

if(!(Test-Path -LiteralPath $projFile)){

Similar errors will occur if the script subsequently accesses the file system without specifying the -LiteralPath switch.

**Comment by davilimap** [comment]
SlowCheetah no longer uses an install script, but relies on NuGet instead.
